Recruiting/Recruiting.web/Models/ErrorViewModel.cs
using System;

namespace Recruiting.web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Recruiting/Recruiting.web/Controllers/ApplicantsController.cs
using Microsoft.AspNetCore.Mvc;
using Recruiting.Data.EfModels;
using Recruiting.Data.EfRepositories.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Recruiting.Web.Controllers
{
    public class ApplicantsController : Controller
    {
        private readonly IEfApplicantRepository _applicantRepository;

        public ApplicantsController(IEfApplicantRepository applicantRepository)
        {
            _applicantRepository = applicantRepository;
        }
        public async Task<IActionResult> List()
        {
            IEnumerable<EfApplicant> applicants = await _applicantRepository.ListAsync();
            
            return View(applicants);
        }
    }
}

Recruiting/Recruiting.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Recruiting.web.Models;

namespace Recruiting.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Recruiting/Recruiting.web/Controllers/JobsController.cs
using Microsoft.AspNetCore.Mvc;
using Recruiting.Data.EfModels;
using Recruiting.Data.EfRepositories.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Recruiting.Web.Controllers
{
    public class JobsController : Controller
    {
        private readonly IEfJobRepository _jobRepository;

        public JobsController(IEfJobRepository jobRepository)
        {
            _jobRepository = jobRepository;
        }
        public async Task<IActionResult> List()
        {
            IEnumerable<EfJob> jobs = await _jobRepository.ListAsync();
            return View(jobs);
        }
    }
}

Recruiting/Recruiting.web/Views/Applicants/List.cshtml
@model IEnumerable<EfApplicant>
@{
}



<h2>Current Applicants</h2>

<div class="table-responsive">
    <table class="table table-striped table-dark">
        <thead>
            <tr class="table-primary">
                <th>
                    Full Name
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Country)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var applicant in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => applicant.LastName)&nbsp;@Html.DisplayFor(modelItem => applicant.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => applicant.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => applicant.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => applicant.Country)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Recruiting/Recruiting.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Recruiting/Recruiting.web/Views/Jobs/List.cshtml
@model IEnumerable<EfJob>
@{
}

<h2>Current Jobs</h2>

<div class="table-responsive">
    <table class="table table-striped table-dark">
        <thead>
            <tr class="table-primary">
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Reference)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Company)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Location)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var job in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => job.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => job.Reference)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => job.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => job.Location)
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Recruiting/Recruiting.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recruiting.Web</title>
    <link rel="stylesheet" href="~/lib/bootswatch/flatly/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="jumbotron text-center mb-0 text-white">
        <h1>The Recruiting Machine</h1>
        <p>Recruit the perfect applicant in less than 5 minutes!!!</p>
    </div>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Recruiting</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Jobs" asp-action="List">Jobs</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" asp-controller="Applicants" asp-action="List">Applicants</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Recruiting.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>